# Generated by Django 6.1.1 on 2026-09-09 19:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kurikulum', models.CharField(max_length=150)),
                ('tahun_ajaran', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Kurikulum',
                'ordering': ['-is_active', '-tahun_ajaran', 'nama_kurikulum'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nama_lengkap', models.CharField(blank=True, max_length=255)),
                ('nip_nrp', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('GADIK', 'Gadik'), ('SERDIK', 'Serdik')], default='SERDIK', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kelas', models.CharField(max_length=50)),
                ('gadik_pembina', models.ForeignKey(blank=True, limit_choices_to={'role': 'GADIK'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelas_binaan', to=settings.AUTH_USER_MODEL)),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kelas', to='lms.kurikulum')),
            ],
            options={
                'verbose_name_plural': 'Kelas',
                'ordering': ['nama_kelas'],
            },
        ),
        migrations.CreateModel(
            name='MataPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_mapel', models.CharField(max_length=20)),
                ('nama_mapel', models.CharField(max_length=100)),
                ('kurikulum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mata_pelajaran', to='lms.kurikulum')),
            ],
            options={
                'verbose_name_plural': 'Mata pelajaran',
                'ordering': ['kode_mapel'],
            },
        ),
        migrations.CreateModel(
            name='ModulBelajar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('file_modul', models.FileField(upload_to='modul/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gadik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modul_dibuat', to=settings.AUTH_USER_MODEL)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modul', to='lms.kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modul', to='lms.matapelajaran')),
            ],
            options={
                'verbose_name_plural': 'Modul belajar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_tugas', models.CharField(max_length=200)),
                ('instruksi', models.TextField()),
                ('file_lampiran', models.FileField(blank=True, upload_to='tugas/lampiran/%Y/%m/')),
                ('deadline', models.DateTimeField()),
                ('bobot', models.PositiveSmallIntegerField(default=100, help_text='Bobot nilai dalam persen.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gadik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tugas_dibuat', to=settings.AUTH_USER_MODEL)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas', to='lms.kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tugas', to='lms.matapelajaran')),
            ],
            options={
                'verbose_name_plural': 'Tugas',
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='PengumpulanTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_tugas', models.FileField(upload_to='pengumpulan/%Y/%m/')),
                ('catatan_serdik', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('catatan_gadik', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('TERKIRIM', 'Terkirim'), ('TERLAMBAT', 'Terlambat'), ('DINILAI', 'Dinilai')], default='TERKIRIM', max_length=10)),
                ('serdik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumpulan_tugas', to=settings.AUTH_USER_MODEL)),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumpulan', to='lms.tugas')),
            ],
            options={
                'verbose_name_plural': 'Pengumpulan tugas',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AnggotaKelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serdik', models.ForeignKey(limit_choices_to={'role': 'SERDIK'}, on_delete=django.db.models.deletion.CASCADE, related_name='keanggotaan_kelas', to=settings.AUTH_USER_MODEL)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='lms.kelas')),
            ],
            options={
                'verbose_name_plural': 'Anggota kelas',
                'constraints': [models.UniqueConstraint(fields=('kelas', 'serdik'), name='unik_anggota_kelas')],
            },
        ),
        migrations.AddConstraint(
            model_name='matapelajaran',
            constraint=models.UniqueConstraint(fields=('kurikulum', 'kode_mapel'), name='unik_kode_mapel_per_kurikulum'),
        ),
        migrations.AddConstraint(
            model_name='pengumpulantugas',
            constraint=models.UniqueConstraint(fields=('tugas', 'serdik'), name='unik_pengumpulan_tugas'),
        ),
    ]
