# Generated by Django 6.1.1 on 2026-09-09 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matapelajaran',
            name='gadik_pengajar',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'GADIK'}, related_name='mata_pelajaran_diampu', to=settings.AUTH_USER_MODEL),
        ),
    ]
