# Generated by Django 6.1.1 on 2026-09-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_matapelajaran_gadik_pengajar'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='anggotakelas',
            name='unik_anggota_kelas',
        ),
        migrations.AddField(
            model_name='customuser',
            name='alamat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='asal_pengiriman',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='anggotakelas',
            constraint=models.UniqueConstraint(fields=('serdik',), name='unik_kelas_per_serdik'),
        ),
    ]
