# Generated by Django 6.1.1 on 2026-09-10 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_backfill_legacy_graders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ujian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('metode', models.CharField(choices=[('ESAI', 'Esai'), ('PILIHAN_GANDA', 'Pilihan Ganda')], max_length=20)),
                ('instruksi', models.TextField()),
                ('waktu_mulai', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('durasi_menit', models.PositiveSmallIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gadik', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ujian_dibuat', to=settings.AUTH_USER_MODEL)),
                ('kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ujian', to='lms.kelas')),
                ('mapel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ujian', to='lms.matapelajaran')),
            ],
            options={
                'verbose_name_plural': 'Ujian',
                'ordering': ['waktu_mulai'],
            },
        ),
    ]
