# Generated by Django 6.1.1 on 2026-09-10 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_ujian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ujian',
            name='deadline',
        ),
        migrations.CreateModel(
            name='SoalUjianEsai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveSmallIntegerField()),
                ('pertanyaan', models.TextField()),
                ('kunci_jawaban', models.TextField()),
                ('bobot', models.PositiveSmallIntegerField(default=10)),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_esai', to='lms.ujian')),
            ],
            options={
                'verbose_name_plural': 'Soal ujian esai',
                'ordering': ['urutan'],
                'constraints': [models.UniqueConstraint(fields=('ujian', 'urutan'), name='unik_urutan_soal_esai_per_ujian')],
            },
        ),
    ]
