# Generated by Django 6.1.1 on 2026-09-10 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_remove_ujian_deadline_soalujianesai'),
    ]

    operations = [
        migrations.AddField(
            model_name='ujian',
            name='pemeriksaan',
            field=models.CharField(choices=[('OTOMATIS', 'Otomatis'), ('MANUAL', 'Manual')], default='MANUAL', max_length=10),
        ),
        migrations.CreateModel(
            name='PengumpulanUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('serdik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumpulan_ujian', to=settings.AUTH_USER_MODEL)),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumpulan', to='lms.ujian')),
            ],
            options={
                'verbose_name_plural': 'Pengumpulan ujian',
            },
        ),
        migrations.CreateModel(
            name='JawabanUjianEsai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.TextField()),
                ('skor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='lms.soalujianesai')),
                ('pengumpulan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_esai', to='lms.pengumpulanujian')),
            ],
            options={
                'verbose_name_plural': 'Jawaban ujian esai',
            },
        ),
        migrations.AddConstraint(
            model_name='pengumpulanujian',
            constraint=models.UniqueConstraint(fields=('ujian', 'serdik'), name='unik_pengumpulan_ujian'),
        ),
        migrations.AddConstraint(
            model_name='jawabanujianesai',
            constraint=models.UniqueConstraint(fields=('pengumpulan', 'soal'), name='unik_jawaban_esai_per_soal'),
        ),
    ]
