# Generated by Django 6.1.1 on 2026-09-10 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_ujian_pemeriksaan_pengumpulanujian_jawabanujianesai_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soalujianesai',
            name='bobot',
        ),
    ]
