# Generated by Django 6.1.1 on 2026-09-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_exam_attempt_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoalUjianPilihanGanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveSmallIntegerField()),
                ('pertanyaan', models.TextField()),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_pilihan_ganda', to='lms.ujian')),
            ],
            options={
                'verbose_name_plural': 'Soal ujian pilihan ganda',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='OpsiUjianPilihanGanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urutan', models.PositiveSmallIntegerField()),
                ('teks', models.CharField(max_length=500)),
                ('is_kunci', models.BooleanField(default=False)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opsi', to='lms.soalujianpilihanganda')),
            ],
            options={
                'verbose_name_plural': 'Opsi ujian pilihan ganda',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='JawabanUjianPilihanGanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pengumpulan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_pilihan_ganda', to='lms.pengumpulanujian')),
                ('opsi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jawaban', to='lms.opsiujianpilihanganda')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='lms.soalujianpilihanganda')),
            ],
            options={
                'verbose_name_plural': 'Jawaban ujian pilihan ganda',
            },
        ),
        migrations.AddConstraint(
            model_name='soalujianpilihanganda',
            constraint=models.UniqueConstraint(fields=('ujian', 'urutan'), name='unik_urutan_soal_pg_per_ujian'),
        ),
        migrations.AddConstraint(
            model_name='opsiujianpilihanganda',
            constraint=models.UniqueConstraint(fields=('soal', 'urutan'), name='unik_urutan_opsi_pg_per_soal'),
        ),
        migrations.AddConstraint(
            model_name='jawabanujianpilihanganda',
            constraint=models.UniqueConstraint(fields=('pengumpulan', 'soal'), name='unik_jawaban_pg_per_soal'),
        ),
    ]
