# Generated by Django 6.1.1 on 2026-09-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_soalujianpilihanganda_opsiujianpilihanganda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jawabanujianesai',
            name='alasan_koreksi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jawabanujianesai',
            name='skor_otomatis',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
