from django.urls import path

from . import views

urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("profil/", views.profil, name="profil"),
    path("kelas/", views.daftar_kelas, name="daftar_kelas"),
    path("kelas/<int:pk>/", views.detail_kelas, name="detail_kelas"),
    path("pengelolaan/siswa/", views.daftar_siswa, name="daftar_siswa"),
    path("pengelolaan/siswa/tambah/", views.tambah_siswa, name="tambah_siswa"),
    path("pengelolaan/siswa/<int:pk>/ubah/", views.ubah_siswa, name="ubah_siswa"),
    path("pengelolaan/", views.pengelolaan_admin, name="pengelolaan_admin"),
    path("pengelolaan/kurikulum/", views.daftar_kurikulum, name="daftar_kurikulum"),
    path("pengelolaan/kurikulum/tambah/", views.tambah_kurikulum, name="tambah_kurikulum"),
    path(
        "pengelolaan/kurikulum/<int:pk>/status/",
        views.ubah_status_kurikulum,
        name="ubah_status_kurikulum",
    ),
    path("pengelolaan/kelas/tambah/", views.tambah_kelas, name="tambah_kelas"),
    path("pengelolaan/kelas/<int:pk>/siswa/", views.kelola_anggota_kelas, name="kelola_anggota_kelas"),
    path(
        "pengelolaan/kelas/<int:pk>/siswa/<int:anggota_pk>/hapus/",
        views.hapus_anggota_kelas,
        name="hapus_anggota_kelas",
    ),
    path("pengelolaan/mata-pelajaran/", views.daftar_mata_pelajaran, name="daftar_mata_pelajaran"),
    path("pengelolaan/mata-pelajaran/tambah/", views.tambah_mata_pelajaran, name="tambah_mata_pelajaran"),
    path("pengelolaan/gadik/", views.daftar_gadik, name="daftar_gadik"),
    path("pengelolaan/gadik/tambah/", views.tambah_gadik, name="tambah_gadik"),
    path("pengelolaan/gadik/<int:pk>/ubah/", views.ubah_gadik, name="ubah_gadik"),
    path("pengelolaan/modul/tambah/", views.tambah_modul_admin, name="tambah_modul_admin"),
    path("modul/", views.daftar_modul, name="daftar_modul"),
    path("modul/tambah/", views.buat_modul, name="buat_modul"),
    path("modul/<int:pk>/ubah/", views.ubah_modul, name="ubah_modul"),
    path("modul/<int:pk>/hapus/", views.hapus_modul, name="hapus_modul"),
    path("ujian/", views.daftar_ujian, name="daftar_ujian"),
    path("ujian/tambah/", views.buat_ujian, name="buat_ujian"),
    path("ujian/<int:pk>/ubah/", views.ubah_ujian, name="ubah_ujian"),
    path("ujian/<int:pk>/mulai/", views.mulai_ujian_esai, name="mulai_ujian_esai"),
    path("ujian/<int:pk>/kerjakan/", views.kerjakan_ujian_esai, name="kerjakan_ujian_esai"),
    path("ujian/<int:pk>/hasil/", views.hasil_ujian, name="hasil_ujian"),
    path("ujian/<int:pk>/export/excel/", views.export_hasil_ujian_excel, name="export_hasil_ujian_excel"),
    path("ujian/<int:pk>/export/pdf/", views.export_hasil_ujian_pdf, name="export_hasil_ujian_pdf"),
    path("ujian/<int:pk>/soal-esai/", views.kelola_soal_esai, name="kelola_soal_esai"),
    path(
        "ujian/<int:pk>/soal-esai/<int:soal_pk>/hapus/",
        views.hapus_soal_esai,
        name="hapus_soal_esai",
    ),
    path("ujian/<int:pk>/soal-pilihan-ganda/", views.kelola_soal_pilihan_ganda, name="kelola_soal_pilihan_ganda"),
    path(
        "ujian/<int:pk>/soal-pilihan-ganda/<int:soal_pk>/hapus/",
        views.hapus_soal_pilihan_ganda,
        name="hapus_soal_pilihan_ganda",
    ),
    path("tugas/tambah/", views.buat_tugas, name="buat_tugas"),
    path("tugas/<int:pk>/", views.detail_tugas, name="detail_tugas"),
    path("tugas/<int:pk>/ubah/", views.ubah_tugas, name="ubah_tugas"),
    path("tugas/<int:pk>/hapus/", views.hapus_tugas, name="hapus_tugas"),
    path("tugas/<int:pk>/kumpulkan/", views.kumpulkan_tugas, name="kumpulkan_tugas"),
    path("tugas/<int:pk>/pengumpulan/", views.daftar_pengumpulan, name="daftar_pengumpulan"),
    path("pengumpulan/<int:pk>/nilai/", views.nilai_pengumpulan, name="nilai_pengumpulan"),
    path("nilai/", views.daftar_nilai, name="daftar_nilai"),
]
